database:
  url: jdbc:mysql://localhost:3306/auth
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver

tables:
  - tableName: ad_account_info
  - tableName: ad_account_auth_info

swaggerConfig:
  swaggerEnable: true
  # API文档类型：swagger, openapi, asyncapi（默认：swagger）
  apiDocType: swagger
  # API文档版本（默认：3.0）
  apiDocVersion: 3.0

outputConfig:
  baseOutputDir: /Users/wangzhuo/Downloads/code
  authorInfo: noWork.fun
  packageUrl: com.imi4u36d
  overwriteEnable: true

ftlFileDir: /Users/wangzhuo/Downloads/ftl

# 自定义属性
customProperties:
  # Lombok支持
  lombokEnable: true
  # 自定义分层后缀
  layerSuffix:
    controller: Controller
    service: Service
    serviceImpl: Impl
    mapper: Mapper
    dto: Dto
    entity: Entity
  # 自定义分层包名称
  layerPackageName:
    dto: dto
    entity: domain
    service: service
    serviceImpl: service.impl
    mapper: mapper
    controller: controller
